/* eslint-disable no-unused-vars */
export enum FormActions {
  setCurrentStep,
  setName,
  setHeight1,
  setWidth1,
  setDoors1,
  setWindows1,
  setHeight2,
  setWidth2,
  setDoors2,
  setWindows2,
  setHeight3,
  setWidth3,
  setDoors3,
  setWindows3,
  setHeight4,
  setWidth4,
  setDoors4,
  setWindows4,
}
